<a href="https://colab.research.google.com/github/devvaii/NLP_sentiment_analysis/blob/main/sentiment_analysis_bert.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
pip install beautifulsoup4 requests

In [24]:
import pandas as pd
import numpy as np
import re
from transformers import AutoTokenizer,AutoModelForSequenceClassification
from bs4 import BeautifulSoup
import requests
import torch
from scipy.special import softmax

In [11]:
tokenizer=AutoTokenizer.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')
model=AutoModelForSequenceClassification.from_pretrained('nlptown/bert-base-multilingual-uncased-sentiment')

tokenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/953 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/872k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/669M [00:00<?, ?B/s]

In [18]:
tokens=tokenizer('I love eating from indian restaurants in Milan',return_tensors='pt',padding=True,truncation=True)
tokens

{'input_ids': tensor([[  101,   151, 11157, 59305, 10195, 12591, 35685, 10104, 15378,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [19]:
results=model(**tokens)
results

SequenceClassifierOutput(loss=None, logits=tensor([[-1.9726, -1.8175, -0.5533,  1.2466,  2.3478]],
       grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [20]:
results.logits

tensor([[-1.9726, -1.8175, -0.5533,  1.2466,  2.3478]],
       grad_fn=<AddmmBackward0>)

In [26]:
results[0]

tensor([[-1.9726, -1.8175, -0.5533,  1.2466,  2.3478]],
       grad_fn=<AddmmBackward0>)

In [33]:
scores_dict={}
scores=results[0][0].detach().numpy()
scores=softmax(scores)
scores


array([0.00938679, 0.01096157, 0.03880923, 0.23475178, 0.7060906 ],
      dtype=float32)

In [34]:
scores[1]

0.010961571

In [37]:
scores_dict={
      'score_very_neg':scores[0],
      'score_neg':scores[1],
      'score_neu':scores[2],
      'score_pos':scores[3],
      'score_very_pos':scores[4]

  }
scores_dict

{'score_very_neg': 0.009386789,
 'score_neg': 0.010961571,
 'score_neu': 0.038809232,
 'score_pos': 0.23475178,
 'score_very_pos': 0.7060906}

In [38]:
int(torch.argmax(results.logits))+1

5